# -*- coding: utf-8 -*-
"""multiple_rag_tk_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mRyYeq9Bx0eiuLyL98U9ranQyxyhfO7F
"""

!pip install datasets rank_bm25 sentence-transformers faiss-cpu --quiet

from datasets import load_dataset
from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

# -------------------------
# 1) Load the dataset
# -------------------------
dataset = load_dataset("Selvakumarduraipandian/Thirukural")
kural_texts = [item["Kural"] for item in dataset["train"]]  # you can also include English

# -------------------------
# 2) Tokenization for BM25
# -------------------------
def simple_tokenize(text):
    return text.lower().split()

corpus_tokens = [simple_tokenize(text) for text in kural_texts if text.strip()]
# Filter out any empty lists
corpus_tokens = [tokens for tokens in corpus_tokens if len(tokens) > 0]

# -------------------------
# 3) BM25 Index
# -------------------------
bm25 = BM25Okapi(corpus_tokens)

# -------------------------
# 4) Embedding model & FAISS index
# -------------------------
embed_model = SentenceTransformer("all-MiniLM-L6-v2")
corpus_embeddings = embed_model.encode(kural_texts, convert_to_numpy=True, show_progress_bar=True)

# Create FAISS index
d = corpus_embeddings.shape[1]
faiss_index = faiss.IndexFlatL2(d)
faiss_index.add(corpus_embeddings)

# -------------------------
# 5) Retrieval functions
# -------------------------
def bm25_search(query, top_k=5):
    query_tokens = simple_tokenize(query)
    scores = bm25.get_scores(query_tokens)
    top_n = np.argsort(scores)[::-1][:top_k]
    return [(kural_texts[i], scores[i]) for i in top_n]

def embedding_search(query, top_k=5):
    query_embedding = embed_model.encode([query], convert_to_numpy=True)
    distances, indices = faiss_index.search(query_embedding, top_k)
    return [(kural_texts[i], float(distances[0][j])) for j, i in enumerate(indices[0])]

def hybrid_search(query, top_k=5):
    bm25_results = bm25_search(query, top_k=top_k*2)
    emb_results = embedding_search(query, top_k=top_k*2)

    # Normalize & combine scores
    combined_scores = {}
    for text, score in bm25_results:
        combined_scores[text] = combined_scores.get(text, 0) + score
    for text, score in emb_results:
        combined_scores[text] = combined_scores.get(text, 0) + (1/(1+score))  # smaller dist → higher score

    sorted_results = sorted(combined_scores.items(), key=lambda x: x[1], reverse=True)[:top_k]
    return sorted_results

# -------------------------
# 6) Chatbot function with RAG
# -------------------------
def rag_chatbot(query, mode="hybrid", top_k=3):
    if mode == "bm25":
        results = bm25_search(query, top_k)
    elif mode == "embedding":
        results = embedding_search(query, top_k)
    else:
        results = hybrid_search(query, top_k)

    # Construct answer (here just showing retrieved Kurals)
    print(f"\n[ Retrieval Mode: {mode.upper()} ]")
    for i, (text, score) in enumerate(results, start=1):
        print(f"{i}. {text}  (score: {score:.4f})")

# -------------------------
# 7) Example usage
# -------------------------
query = "அறம் பற்றிய குறள்"
rag_chatbot(query, mode="bm25")
rag_chatbot(query, mode="embedding")
rag_chatbot(query, mode="hybrid")

!pip install datasets sentence-transformers scikit-learn ipywidgets --quiet

import json
import re
import numpy as np
from scipy.sparse import csr_matrix
from collections import Counter
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
from datasets import load_dataset
import ipywidgets as widgets
from IPython.display import display, clear_output

dataset = load_dataset("Selvakumarduraipandian/Thirukural")
kurals = dataset['train']

class BaseRetriever:
    def __init__(self, kurals, field='Couplet'):
        self.kurals = kurals
        self.field = field
    def retrieve(self, query, top_k=5):
        raise NotImplementedError

    def format_result(self, res):
        return (f"Kural {res['ID']}: {res['Kural']} (English: {res['Couplet']})\n"
                f"Explanation: {res['Vilakam']}\n")

class KeywordRetriever(BaseRetriever):

    def retrieve(self, query, top_k=5):
        query_words = set(re.findall(r'\w+', query.lower()))
        scores = []
        for kural in self.kurals:
            text = kural[self.field].lower()
            match_count = sum(1 for word in query_words if word in text)
            scores.append(match_count)


        top_indices = np.argsort(scores)[-top_k:][::-1]

        return [self.kurals[int(i)] for i in top_indices if scores[i] > 0]

class TFIDFRetriever(BaseRetriever):

    def __init__(self, kurals, field='Couplet'):
        super().__init__(kurals, field)
        self.vectorizer = TfidfVectorizer()
        self.tfidf_matrix = self.vectorizer.fit_transform([kural[self.field] for kural in kurals])

    def retrieve(self, query, top_k=5):
        query_vec = self.vectorizer.transform([query])
        similarities = cosine_similarity(query_vec, self.tfidf_matrix).flatten()
        top_indices = np.argsort(similarities)[-top_k:][::-1]

        return [self.kurals[int(i)] for i in top_indices]

class EmbeddingRetriever(BaseRetriever):

    def __init__(self, kurals, field='Couplet'):
        super().__init__(kurals, field)
        self.model = SentenceTransformer('all-MiniLM-L6-v2')
        self.embeddings = self.model.encode([kural[self.field] for kural in kurals])

    def retrieve(self, query, top_k=5):
        query_emb = self.model.encode([query])
        similarities = np.dot(self.embeddings, query_emb.T).flatten()
        top_indices = np.argsort(similarities)[-top_k:][::-1]

        return [self.kurals[int(i)] for i in top_indices]

retrievers = {
    'Keyword': KeywordRetriever(kurals),
    'TF-IDF': TFIDFRetriever(kurals),
    'Embedding': EmbeddingRetriever(kurals),
}

retriever_dropdown = widgets.Dropdown(
    options=list(retrievers.keys()),
    value='Keyword',
    description='Retriever:',
    style={'description_width': 'initial'}
)

query_input = widgets.Text(
    value='',
    placeholder='Enter query (e.g., knowledge and learning)',
    description='Query:',
    style={'description_width': 'initial'}
)

output = widgets.Output()

def on_submit(change):
    with output:
        clear_output()
        selected_retriever = retrievers[retriever_dropdown.value]
        query = query_input.value.strip()
        if query:
            try:
                results = selected_retriever.retrieve(query, top_k=5)
                if results:
                    for res in results:
                        print(selected_retriever.format_result(res))
                else:
                    print("No relevant kurals found for the query.")
            except Exception as e:
                print(f"Error during retrieval: {str(e)}")
        else:
            print("Please enter a query.")

submit_button = widgets.Button(description="Retrieve")
submit_button.on_click(on_submit)

# Display UI
display(retriever_dropdown, query_input, submit_button, output)